export type NotionRichText = {
  plain_text?: string;
  text?: { content?: string };
};

export type NotionProperty = {
  type: string;
  title?: NotionRichText[];
  rich_text?: NotionRichText[];
  select?: { name: string } | null;
  multi_select?: { name: string }[];
  number?: number | null;
  url?: string | null;
  date?: { start: string } | null;
  checkbox?: boolean;
  relation?: { id: string }[];
  files?: { type: "file" | "external"; file?: { url: string }; external?: { url: string } }[];
  rollup?: { type: string; number?: number | null };
};

export type NotionPage = {
  object: "page";
  id: string;
  url: string;
  created_time?: string;
  archived?: boolean;
  in_trash?: boolean;
  properties: Record<string, NotionProperty>;
};

export type Story = {
  id: string;
  slug: string;
  notionSlug: string;
  title: string;
  publishedAt: string | null;
  createdAt: string;
  authorId: string | null;
  authorName: string | null;
  sagaId: string | null;
  sagaNumber: number | null;
  relatedStoryIds: string[];
  filterValues: Record<string, string[]>;
  coverUrl: string | null;
  hook: string;
  synopsis: string;
  review: string;
  idealFor: string;
  avoidIf: string;
  warningContext: string;
  warnings: string[];
  subgenres: string[];
  tropes: string[];
  relationshipTypes: string[];
  kuSpain: boolean;
  relationshipDynamics: string[];
  loveInterestTraits: string[];
  rating: number | null;
  darkness: number | null;
  spice: number | null;
  toxicity: number | null;
  violence: number | null;
  impact: number | null;
  plot: number | null;
  writing: number | null;
  characters: number | null;
  romance: number | null;
  originality: number | null;
  originalTitle: string;
  originalYear: number | null;
  chapterCount: number | null;
  pageCount: number | null;
  format: string[];
  publisher: string;
  amazonUrl: string | null;
  officialUrl: string | null;
};

export type Author = {
  id: string;
  slug: string;
  name: string;
  bio: string;
  intro: string;
  country: string[];
  specialties: string[];
  website: string | null;
  photoUrl: string | null;
  publicationTypes: string[];
  storyCount: number | null;
  instagram: string | null;
  tiktok: string | null;
  wattpad: string | null;
  goodreads: string | null;
  amazonUrl: string | null;
  verifiedAt: string | null;
  featuredCollectionId: string | null;
  storyIds: string[];
  sagaIds: string[];
};

export type Saga = {
  id: string;
  slug: string;
  name: string;
  description: string;
  intro: string;
  authorIds: string[];
  storyIds: string[];
  readingOrder: string | null;
  originalTitle: string;
  sagaType: string | null;
  status: string | null;
  bookCount: number | null;
  bookTitles: string[];
  spanishAvailability: string | null;
  kindleUnlimited: string | null;
  standalone: string | null;
  bookRelationship: string | null;
  whyReadInOrder: string;
  faqs: { question: string; answer: string }[];
  coverUrl: string | null;
  seoTitle: string;
  metaDescription: string;
};

export type SeoPage = {
  id: string;
  slug: string;
  path: string;
  hasExplicitPath: boolean;
  pageType: string;
  pageFormat: string;
  topic: string;
  priority: number | null;
  publishedAt: string | null;
  createdAt: string;
  section: string;
  title: string;
  contentTitle: string;
  heading: string;
  description: string;
  summary: string;
  intro: string;
  conclusion: string;
  cta: string;
  faqs: string;
  indexable: boolean;
  dynamicCollection: boolean;
  relatedStoryIds: string[];
  mainStoryIds: string[];
  authorIds: string[];
  sagaIds: string[];
  filter1: { field: string; operator: string; value: string };
  filter2: { field: string; operator: string; value: string };
};
